
"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# First Changes
import os 
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR.parent / '.env')

IS_VERCEL = os.environ.get('VERCEL') == '1' or 'VERCEL' in os.environ


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False' if IS_VERCEL else 'True').strip().lower() in {
    '1', 'true', 'yes', 'on',
}

if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured('Set DJANGO_SECRET_KEY in the environment.')
    SECRET_KEY = 'django-insecure-local-development-only-change-me'

def csv_env(name, defaults=()):
    value = os.environ.get(name)
    if value is None:
        return list(defaults)
    return [item.strip() for item in value.split(',') if item.strip()]


vercel_hosts = [
    os.environ[name]
    for name in ('VERCEL_URL', 'VERCEL_PROJECT_PRODUCTION_URL')
    if os.environ.get(name)
]
ALLOWED_HOSTS = csv_env(
    'DJANGO_ALLOWED_HOSTS',
    ['localhost', '127.0.0.1'],
)
ALLOWED_HOSTS.extend(host for host in vercel_hosts if host not in ALLOWED_HOSTS)
CSRF_TRUSTED_ORIGINS = csv_env(
    'CSRF_TRUSTED_ORIGINS',
    [
        'http://localhost:8000',
        'http://127.0.0.1:8000',
    ],
)
CSRF_TRUSTED_ORIGINS.extend(
    f'https://{host}'
    for host in vercel_hosts
    if f'https://{host}' not in CSRF_TRUSTED_ORIGINS
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shopsphere' ##Second Changes App Name
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'e_commerce.urls'##Check Changes Project name

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], ##Third Changes
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shopsphere.context_processors.announcements',
            ],
        },
    },
]

WSGI_APPLICATION = 'e_commerce.wsgi.application'##Check Changes Project Name

AUTH_USER_MODEL = 'shopsphere.CustomUser'
import shutil

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if IS_VERCEL:
    tmp_db = Path('/tmp/db.sqlite3')
    source_db = BASE_DIR / 'db.sqlite3'
    if not source_db.exists():
        source_db = BASE_DIR / 'e_commerce' / 'db.sqlite3'

    if source_db.exists() and not tmp_db.exists():
        try:
            shutil.copy2(source_db, tmp_db)
        except Exception as e:
            print(f"Error copying DB to /tmp: {e}")
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': tmp_db if tmp_db.exists() else source_db,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] ##Fourth Changes

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Gmail SMTP backend enabled
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# Allow DD/MM/YYYY format for dates
DATE_INPUT_FORMATS = [
    '%d/%m/%Y',  # '29/09/2003'
    '%d-%m-%Y',  # '29-09-2003'
    '%Y-%m-%d',  # '2003-09-29'
]

# CSRF & Session Settings
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SECURE = not DEBUG

# Session Engine Configuration for Serverless / Vercel persistence
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
SESSION_COOKIE_NAME = 'shopsphere_sessionid'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 1209600
SESSION_SAVE_EVERY_REQUEST = True


# Custom User Model
AUTH_USER_MODEL = 'shopsphere.CustomUser'

# Razorpay API credentials
RAZORPAY_API_KEY = os.environ.get('RAZORPAY_API_KEY', '')
RAZORPAY_API_SECRET = os.environ.get('RAZORPAY_API_SECRET', '')

# Cloudinary Configuration for Product Media Hosting
# Create Cloudinary Credentials (required for hosting and managing product images/media)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY', ''),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', ''),
}

# Un-comment the line below when deploying to production with Cloudinary
# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
