
"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# First Changes
import os 
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-**nj1_v0qudh+93myc7=3@+s&l)dn(6a9esk10tz3v$rl#55zc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://shopsphere.com:8000',
    'http://shopsphere.com',
    'https://shopsphere.com',
    'https://*.ngrok-free.app',
    'https://*.trycloudflare.com',
    'https://*.github.dev',
    'https://*.app.github.dev',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shopsphere' ##Second Changes App Name
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'e_commerce.urls'##Check Changes Project name

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], ##Third Changes
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shopsphere.context_processors.announcements',
            ],
        },
    },
]

WSGI_APPLICATION = 'e_commerce.wsgi.application'##Check Changes Project Name

AUTH_USER_MODEL = 'shopsphere.CustomUser'
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',

        # 'ENGINE': 'django.db.backends.postgresql',
        # 'NAME': 'InventoryManagement',
        # 'USER': 'postgres',
        # 'PASSWORD': 'root',
        # 'HOST': 'localhost',
        # 'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] ##Fourth Changes

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Gmail SMTP backend enabled
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'supportshopsphere@gmail.com'
EMAIL_HOST_PASSWORD = 'vefw tdis lewq lpso'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'vs2734514@gmail.com'

# Allow DD/MM/YYYY format for dates
DATE_INPUT_FORMATS = [
    '%d/%m/%Y',  # '29/09/2003'
    '%d-%m-%Y',  # '29-09-2003'
    '%Y-%m-%d',  # '2003-09-29'
]

# CSRF Settings for development
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SECURE = False

# Custom User Model
AUTH_USER_MODEL = 'shopsphere.CustomUser'

# Razorpay API credentials
RAZORPAY_API_KEY = 'rzp_test_T7ub9uRXOT69Du'
RAZORPAY_API_SECRET = 'r071X4HV5n7so70Qmstrg54v'

# Cloudinary Configuration for Product Media Hosting
# Create Cloudinary Credentials (required for hosting and managing product images/media)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dpxvxlghh',
    'API_KEY': '123456789012345',
    'API_SECRET': 'abc-1234567890abcdefghijklmnopqrstuv',
}

# Un-comment the line below when deploying to production with Cloudinary
# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'


