# Generated by Django 6.0.5 on 2026-06-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsphere', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Announcement text (e.g. Free Shipping All Over India)', max_length=255)),
                ('link', models.URLField(blank=True, help_text='Optional link when the bar is clicked', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designate if this announcement is displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
