# Generated by Django 6.0.5 on 2026-06-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsphere', '0005_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designate if this announcement is displayed'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
