# Generated by Django 6.0.5 on 2026-06-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsphere', '0006_alter_announcement_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload gallery image', upload_to='gallery/')),
                ('title', models.CharField(blank=True, help_text='Optional caption or title', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_image', models.ImageField(help_text='Upload employee photo', upload_to='team/')),
                ('employee_name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
