# Generated by Django 6.0.5 on 2026-06-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsphere', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.TextField(default='Order Items'),
        ),
    ]
